/* Generated By:JavaCC: Do not edit this line. CMMCompilerTreeConstants.java Version 5.0 */
package com.xjt.compiler;
public interface CMMCompilerTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROCEDURE = 1;
  public int JJTBLOCK = 2;
  public int JJTSTATEMENT = 3;
  public int JJTDECLARATION = 4;
  public int JJTASSIGNMENT = 5;
  public int JJTEXPRESSION = 6;
  public int JJTCHOICE = 7;
  public int JJTCONDITION = 8;
  public int JJTTERM = 9;
  public int JJTFACTOR = 10;


  public String[] jjtNodeName = {
    "Start",
    "Procedure",
    "Block",
    "Statement",
    "Declaration",
    "Assignment",
    "Expression",
    "Choice",
    "Condition",
    "Term",
    "Factor",
  };
}
/* JavaCC - OriginalChecksum=132f55a6bc7bd87395a0eaba1152ea3b (do not edit this line) */
